### ISSUE TITLE
Support working without a System Console

### ISSUE THREAD

**Issue by mrlacey** [mrlacey/VSConsole#18]
X-Ref: #17 

Enable the use of the library in an application that doesn't have access to `System.Console`.

This is for scenarios where a Console type output is useful for debugging but no actual Console is available.

Implementation note: Add a `VSDebugConsole` that is the same as `VSConsole` but doesn't have the internal calls to `System.Console.*`

**Comment by mrlacey** [comment]
If you now upgrade to the `1.1.0` version of the VSConsole NuGet library you can use `using Console = VSDebugConsole.Console;` and  this will do everything as before but with no dependency on `System.Console` and so can be used in any app.

/cc @hguptauk

**Comment by hguptauk** [comment]
Thank You @mrlacey!
