### ISSUE TITLE
Does it only work for projects created in C# language?

### ISSUE THREAD

**Issue by mingyEx** [mrlacey/VSConsole#19]
I'm from https://stackoverflow.com/a/72021827/13792395 and I don't see a similar description on the project homepage on github (about the languages it supports)
//I don't know if this is because I don't have the components needed for c# development installed, I'm installing

**Comment by mingyEx** [comment]
I installed .NET desktop development via Visual Studio Installer
But I still can't get it to work

**Comment by mingyEx** [comment]
I re-read it and I found myself using this plugin in a wrong way, I should have followed the instructions at https://stackoverflow.com/a/72021827/13792395 exactly,
Add VSCodeExtension to VisualStudio
Add VSCode NugetPackage reference in your project.

I don't have a problem now, what I'm looking for is a solution that can be used by a c++ project.

**Comment by mrlacey** [comment]
I'm not smart enough to use C++. 😉 
I know it works with C# and I don't see any reason it won't work with VB.Net and F#. 
In theory, it works with any language that uses .NET and would call `System.Console.*` to output to the console or `System.Diagnostics.Debug.*` to write debug output. 
If it doesn't work with another programming language, it should be possible to build a simple integration by creating a library that can create output that ends up in the VIsual Studio Debug window.

**Comment by mingyEx** [comment]
Would you like to implement a library for C++ console programs to provide the same functionality! I swear I'll advertise it to a lot of people

**Comment by mrlacey** [comment]
> Would you like to implement a library for C++ console programs to provide the same functionality! I swear I'll advertise it to a lot of people

If you can provide an example C++ console app that writes to the Console and Debug windows I'll see what I can do.

**Comment by mingyEx** [comment]
Do you know IDEA, when I finish writing a program and press the run button, it will output the result to a sub-window of the IDE instead of a separate window that pops up.
I wish there were plugins to achieve the same in visual studio.

**Comment by mrlacey** [comment]
> Do you know IDEA, when I finish writing a program and press the run button, it will output the result to a sub-window of the IDE instead of a separate window that pops up. I wish there were plugins to achieve the same in visual studio.

I don't know IDEA.
Are you now asking about something else, rather than making this work from C++?

**Comment by mingyEx** [comment]
I mean, for a simplest program like
````cpp
int main()
{
cout<<"hello,spice";
}
````
When I create a `Console App` and copy the code to the file, and try to run it, a `Microsoft Visual Studio Debug Console` will pop up, in which it will display `hello, spice`, the function I want is, `hello, spice` will appear in some sub-window of the IDE, such as `output-window` instead of `Debug Console`

**Comment by mrlacey** [comment]
This project does try and provide a solution for the scenario you describe, but it does it by creating a separate version of the static class (`System.Console`) that .NET apps use to write to the console. 
As C++ uses a different approach to write to the console window it is not possible/practical to create a version of this library for use within a C++ codebase.
