### ISSUE TITLE
I can't get it working with Visual Studio 2022 17.4.0 Preview 2.1

### ISSUE THREAD

**Issue by huanlin** [mrlacey/VSConsole#20]
Visual Studio 2022 17.4.0 Preview 2.1
OS: Windows 11 64 bit

Steps:

1. Create a new C# Console project, targeting .NET 7.
2. Run application with Debug mode. 
3. I can see output in Console window, but nothing in the VSCode window.

**Comment by AvtsVivek** [comment]
Yes, I experience the same. I installed the [VsConsole Nuget](https://www.nuget.org/packages/VSConsole/) package as well to the console application that I created. But still not working. Not sure what I am missing.

**Comment by mrlacey** [comment]
I just created a new project in 17.6.1, and it worked fine.

If it's not working for you, please can you provide details of the type of project you're trying to use it in and, if possible, example code.

**Comment by mrlacey** [comment]
Closing as no information is available to investigate further.
Feel free to reopen if/when more details about recreating the issue are available.
