### ISSUE TITLE
Missing Console methods

### ISSUE THREAD

**Issue by mortensp** [mrlacey/VSConsole#22]
I ran in to two missing methods in VSConsole:

![image](https://github.com/mrlacey/VSConsole/assets/2102113/82489ff2-2884-4e22-9485-5757b720fe0a)

**Comment by mrlacey** [comment]
Version 1.2.0 (just released to NuGet) adds support for:

- IsErrorRedirected
- IsInputRedirected
- IsOutputRedirected
- InputEncoding
- OutputEncoding
